### ISSUE TITLE
RxJava based DataFetcher ?

### ISSUE THREAD

**Issue by rogergl** [grooviter/gql#16]
Would it be possible to use  an RX based observer for a DataFetcher ? For example using the mongo.rx client would return an Observer:

```
Observable<Success> insertIntoTest(Document document) {
        return collection.insertOne(document)
    }
```

How would that work with a DataFetcher ?

**Comment by mariogarcia** [comment]
MMMmmm although `DataFetcher` is a functional interface returning potentially any type

```groovy
package graphql.schema;

public interface DataFetcher<T> {
    T get(DataFetchingEnvironment environment);
}
```
**However** underlying GraphQL-java implementation does not support asynchronous execution at the moment. 

Having said that, It could make sense to start thinking about the possibility to have a non blocking api supporting the future implementation of GraphQL java (https://github.com/graphql-java/graphql-java/issues/324). 

I can imagine having a DataFetcher signature like:

```groovy
public interface CompletableDataFetcher<T> {
    CompletableFuture<T> get(DataFetchingEnvironment environment);
}
```
and then (using your Observable example):

```groovy
fetcher { DataFetchingEnvironment env ->
   GqlRx.toCompletableFuture(insertIntoTest(collection.insertOne))
}
```
or some node added to the dsl (maybe through an extension) doing the conversion between `Observable` -> `CompletableFuture` transparent  to you:

```groovy
fetcherRx { DataFetchingEnvironment env ->
   insertIntoTest(collection.insertOne)
}
```

In the meantime I'm afraid the only thing you can do is to block your call, extract the value and make the data fetcher to return that value.

```groovy
fetcher { DataFetchingEnvironment env ->
  insertIntoTest(collection.insertOne).blockingSingle()
}
```
What do you think ?
