### ISSUE TITLE
Add relay abstractions

### ISSUE THREAD

**Issue by mariogarcia** [grooviter/gql#2]
As starting point it would be enough by creating a DSL on top of `graphql-java`'s `relay` package and evolve from that.

**Comment by mrcirillo** [comment]
Is ```graphql-java``` caught up with ```relay-modern```? From what I can tell the backend should be mostly the same with the exception of cached queries and a "connection" being a directive rather than an intermediate type.

**Comment by mariogarcia** [comment]
Hi @mrcirillo 

In reality the implementation of relay could be done from scratch using just the `graphql` part of the `graphql-java` implementation, not the `relay` implementation they did on top of that.

I need  to see the current state of `relay` and decide what to do. Maybe it makes more sense to do my own implementation of relay instead of delegating on `graphql-java`'s implementation so that `gql` won't depend on `graphql-java` on this specific part. I don't know we'll see.

BTW: Thanks for the feedback

**Comment by mrcirillo** [comment]
I wrote a toy DSL that partially covers graphql-java for my project but your implementation is much better. Since I am currently converting said-project to relay-modern I will add a GQL dependency as well and let you know what I learn!

**Comment by mariogarcia** [comment]
Nice :smile: 

Looking forward to hearing about your results

**Comment by mariogarcia** [comment]
@mrcirillo I've created a basic Relay/Classic implementation in the dsl (version `0.1.8-alpha`). I'd love to hear your comments.

**Comment by mrcirillo** [comment]
@mariogarcia Great work! I've sidelined my (fairly distracted) conversion to relay/modern in order to use these new additions. Should be quick. I'll let you know if I come up with anything you haven't already thought of
