### ISSUE TITLE
Bug in DSL.buildQuery 

### ISSUE THREAD

**Issue by fedepia** [grooviter/gql#22]
Hi guys, I would like to use GQL just as a markup builder for GraphQL in Groovy.

Have found this `query builder` in the documentation (https://grooviter.github.io/gql/docs/html5/index.html#_query_builders). 

However, I tested different queries but it generates a wrong output.

For instance, this is a valid GraphQL query I wanted to generate:
```
{
  searchOrders (filter: {status: COMPLETED, type: NEW}) {
    id
    status
  }
}
```

When I write the code for it:
```
String queryString = DSL.buildQuery {
            query('searchOrders', [filter: [status: 'COMPLETED', type: 'NEW']]) {
                returns(Order) {
                    id
                    status
                }
            }
        }
```

This is the generated string:
```
{  searchOrders (filter: [status:COMPLETED, type:NEW]) { 
        id
        status
 } 
 }
```
As you can see, this GraphQL syntax is invalid since it is printing square brackets instead of curly braces.

On the other hand, I found no way to build strings for mutations. Is there any way to do this?

**Comment by mariogarcia** [comment]
Oh I see, thanks for reporting it. I'll take a look ASAP.  

About how to create mutations, as far as I remember `DSL.buildQuery` was meant only for queries, not for mutations. I guess at the moment is a missing feature. I'm keeping that in mind for next version.

**Comment by fedepia** [comment]
Hi Mario, great thanks a lot.

Regarding the mutations, I think having something like this might work:

```groovy
String buildMutation(Closure c) {
    "mutation ${DSL.buildQuery(c)}"
}
```

**Comment by mariogarcia** [comment]
Yeah it makes sense :)

I'm opening a minor branch to fix the former and add the latter.
