### ISSUE TITLE
Avoid Defaulted AssertNotNull when there are no variables to pass with query

### ISSUE THREAD

**Issue by michaelschlies** [grooviter/gql#27]
https://github.com/grooviter/gql/blob/7982dc446476a2c95c23fbe57dec2c0f913b84e4/gql-ratpack/src/main/java/gql/ratpack/GraphQLHandlerUtil.java#L67

This line should look more like 
`Map<String,Object> variables = (Map<String,Object>) payload.getOrDefault("variables", new HashMap<String, Object>())` to avoid an AssertNotNullException in GraphQL handling.

**Comment by mariogarcia** [comment]
I'm fixing this now. I'm taking your changes and adding a test to it. Thanks @michaelschlies ! I'm releasing a new version during the weekend.
