### ISSUE TITLE
QueryBuilder: How to build nested queries?

### ISSUE THREAD

**Issue by deiga** [grooviter/gql#36]
Most GQL APIs have nested objects and I'm puzzled by how to build these queries.
Here is an example of getting trying to get Pull Requests from the Github API:
```
String queryString = DSL.buildQuery {
    query('repository', [owner: 'foobar', name: 'baz']) {
      returns {
        query('pullRequests', [first: 10, headRefName: 'master', state: ['OPEN']]) {
          returns {
            totalCount
          }
        }
      }
    }
  }
```

But this generates a string like `"{  pullRequests (first: 10,headRefName: \"master\",state: [OPEN]) { \n \ttotalCount\n } \n repository (owner: \"foobar\",name: \"baz\") { \n  } \n }"`
Which is clearly incorrect. I tried without the `returns` for the upper query, but it's a required field

**Comment by mariogarcia** [comment]
@deiga I'll look into it

**Comment by antonbulauski** [comment]
@mariogarcia, is there any update on that by chance? I would love to have this feature because the current implementation does not support nested queries :)

**Comment by mariogarcia** [comment]
Hi :wave:

Taking your example as the goal to achieve I would like to discuss a couple of things, I haven't worked with GraphQL in a while and would like to make sure I got this right:

```groovy
String queryString = DSL.buildQuery {
    query('repository', [owner: 'foobar', name: 'baz']) {
      returns {
        query('pullRequests', [first: 10, headRefName: 'master', state: ['OPEN']]) {
          returns {
            totalCount
          }
        }
      }
    }
  }
```

The output for that nested query, Should it be like the following ?

```graphql
 {
      repository(owner: "foobar", name: "baz") {
        pullRequests(first: 10, headRefName: "master", state: [OPEN]) {
          totalCount
        }
     }
}
```

How nested queries should be rendered alongside attributes ?  Imagine a query like:

```groovy
String queryString = DSL.buildQuery {
    query('repository', [owner: 'foobar', name: 'baz']) {
      returns {
       starsCount
       forksCount
        query('pullRequests', [first: 10, headRefName: 'master', state: ['OPEN']]) {
          returns {
            totalCount
          }
        }
      }
    }
  }
```

Should the output be like this ?

```graphql
 {
      repository(owner: "foobar", name: "baz") {
        starsCount
        forksCount
        pullRequests(first: 10, headRefName: "master", state: [OPEN]) {
          totalCount
        }
     }
}
```

What about aliases ? Are allowed in nested queries ? If so, this query:

```groovy
String queryString = DSL.buildQuery {
    query('repository', [owner: 'foobar', name: 'baz']) {
      returns {
       starsCount
       forksCount
        query('pullRequests', [first: 10, headRefName: 'master', state: ['OPEN']]) {
          returns {
            totalCount
          }
          alias 'prs'
        }
      }
      alias 'repo'
    }
  }
```
Would produce:

```graphql
 {
      repo: repository(owner: "foobar", name: "baz") {
        starsCount
        forksCount
        prs: pullRequests(first: 10, headRefName: "master", state: [OPEN]) {
          totalCount
        }
     }
}
```

If all of the above is correct, I think I can have time to add this feature.

**Comment by antonbulauski** [comment]
@mariogarcia, yes, all of the above is absolutely correct. Thank you!
